services:
  - type: web
    name: curestock-app
    env: python
    region: oregon # Replace with your preferred region
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app
    runtime: python3.11
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        value: postgresql://curestock_1_user:30ojM7FOojsrncsOMGJcmkaZ9icLuN2Y@dpg-d03trh6uk2gs73cldm1g-a.oregon-postgres.render.com/curestock_1
      - key: DEBUG
        value: False
      - key: RENDER
        value: true
      - key: MIGRATION_SECRET
        generateValue: true
    autoDeploy: true 