services:
  - type: web
    name: curestock-app
    env: python
    region: oregon # Replace with your preferred region
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: RENDER
        value: true
      - key: MIGRATION_SECRET
        generateValue: true
    autoDeploy: true 