services:
  - type: web
    name: curestock-app
    env: python
    region: oregon # Replace with your preferred region
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn myproject.wsgi:application
    runtime: python3.11
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: RENDER
        value: true
      - key: MIGRATION_SECRET
        generateValue: true
    autoDeploy: true 