services:
  - type: web
    name: curestock-app
    env: python
    region: oregon # Replace with your preferred region
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn myproject.wsgi:application
    runtime: python3.11
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: curestock_db
          property: connectionString
      - key: DEBUG
        value: False
      - key: RENDER
        value: true
      - key: MIGRATION_SECRET
        generateValue: true
      - key: RUN_MIGRATIONS_ON_STARTUP
        value: false
    autoDeploy: true

  - type: postgres
    name: curestock_db
    region: oregon
    plan: free
    ipAllowList: [] # Only allow internal connections
    maxmemoryPolicy: noeviction 