# Generated by Django 5.1.4 on 2025-04-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("manufacturer", models.CharField(max_length=200)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price in Rupees", max_digits=10
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("is_discontinued", models.BooleanField(default=False)),
                (
                    "medicine_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("pack_size", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "composition1",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "composition2",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
    ]
