# Generated by Django 5.1.4 on 2025-04-21 19:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("duration", models.IntegerField(default=0)),
                ("call_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("follow_up", models.BooleanField(default=False)),
                ("summary", models.TextField(blank=True)),
                ("transcript", models.TextField(blank=True)),
                ("recording_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["-call_time"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=200)),
                ("quantity", models.CharField(max_length=50)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("pickup", "Pickup"), ("delivery", "Delivery")],
                        default="pickup",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("ready", "Ready for Pickup/Delivery"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="myapp.call",
                    ),
                ),
            ],
        ),
    ]
